
services:
  backend:
    build: .
    container_name: flask_backend
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      FLASK_APP: backend.app
      FLASK_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - .:/backend
    command: ["python", "app.py"]

  db:
    image: postgres:13
    container_name: flask_postgres
    restart: always
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
